### ISSUE TITLE
`master` build failing

### ISSUE THREAD

**Issue by BanzaiMan** [CHH/php-build#264]
The build of `master` started failing a few days ago. For example, https://travis-ci.org/travis-ci/php-src-builder/builds/52377722.

I've dumped the build log here: https://travis-ci.org/travis-ci/php-src-builder/builds/54728768#L134-L171

As a result, Travis CI's PHP nightly build has not been updated the last few days. My initial guess is that the cause is attributable to PHP source itself, but I thought this project would like to know about the failure as well.

**Comment by Tyrael** [comment]
seems to be related to https://travis-ci.org/php/php-src/jobs/54700956

**Comment by Danack** [comment]
To be clear, the developer is investigating the issue.

**Comment by Tyrael** [comment]
should be fixed:
http://news.php.net/php.internals/85191
http://git.php.net/?p=php-src.git;a=commit;h=d6bb5c2cd48b9df0a3a7c19843ca2d5e6703f55d
let us know if you can still reproduce the problem!

**Comment by BanzaiMan** [comment]
I just reran the build, and it appears to fail similarly. https://travis-ci.org/travis-ci/php-src-builder/builds/54728768

**Comment by Danack** [comment]
Hi @BanzaiMan ,

The initial issue was caused by a bug in some optimization code that was only shown when PHP is compiled with a version of GCC before 4.8.0. The fix was to not use this optimized code, unless the version of GCC is 4.8.0 or greater. 

The PHP src build seems to be building just fine here: https://travis-ci.org/php/php-src/builds

Obviously the environment is slightly different for the build you're doing; the PHP team haven't been able to reproduce this issue. Please could you provide the config.log, which should contain the GCC version the failing environment is using, as well as the build log?

cheers
Dan

**Comment by BanzaiMan** [comment]
@Danack Thanks for the information.

The options the builder uses is given in this repository: https://github.com/CHH/php-build/blob/aa055c8895a126faadd619f417973694634dcc4e/share/php-build/default_configure_options (except that we [replace `--without-pear` with `--with-pear`](https://github.com/travis-ci/php-src-builder/blob/9cead0c2c2256268728cd27865c64d724ceb0cf6/.travis.yml#L7)).

php-build also does extra work (https://github.com/CHH/php-build/blob/aa055c8895a126faadd619f417973694634dcc4e/share/php-build/definitions/master), but I do not think any of these definitions influences the configuration.

**Comment by Danack** [comment]
Ah - I just realised the version of GCC that you're using is listed already as `gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3`

And the step your nightly build is failing on is "install-pear-installer" which the PHP src Travis build is skipping as it isn't enabled - due to timeout issues I believe.

Which gives some stuff that I'll try to investigate.

**Comment by nikic** [comment]
Build should hopefully work again (see https://github.com/php/php-src/commit/4b9299d155316e4e49d87d3941eab1ca95b2462a).

**Comment by BanzaiMan** [comment]
Yes!!! https://travis-ci.org/travis-ci/php-src-builder/builds/55190598

Thanks for your help, everyone!
